version: '2'
services:
    testapp-app:
        image: testapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testapp-mysql:3306/testapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testapp-mysql:
        extends:
            file: mysql.yml
            service: testapp-mysql
